language: python

python:
  - 3.6.1

install:
  - pip install -r requirements.txt
  - nvm install 9.2.0
  - npm install --no-optional

before_script:
  - sleep 15
  - npm run seed

script:
  - npm run build
  - npm run production &
  - npm run test

services:
  - mongodb